import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Start Here',
      link: {
        type: 'generated-index',
        title: 'Start Here',
        description: 'New to XDC? Blockchain basics, XDC architecture, gas and fees, and the glossary.',
      },
      items: [{type: 'autogenerated', dirName: 'learn'}],
    },
    {
      type: 'category',
      label: 'Developers',
      link: {
        type: 'generated-index',
        title: 'Developers',
        description: 'Build on XDC: smart contracts, RPC endpoints, SDKs, wallets, and the API reference.',
      },
      items: [
        {type: 'autogenerated', dirName: 'smart-contracts'},
        'xdc-chain/developers/quick-guide',
        'xdc-chain/developers/usdc-quickstart',
        'xdc-chain/developers/rpc',
        'xdc-chain/developers/mainnetrpc',
        'xdc-chain/developers/apothemrpc',
        'xdc-chain/developers/devnetrpc',
        'xdc-chain/developers/wallet-configuration',
        'xdc-chain/developers/getxdclisted',
        'xdc-chain/developers/xdposchain_privatenet',
        'xdc-chain/developers/xdc3js-sdk',
        'xdc-chain/developers/websocket-events',
        'xdc-chain/developers/explorer-guide',
        'xdc-chain/developers/multisig',
        'xdc-chain/developers/bridges',
        'xdc-chain/developers/mobile-integration',
        'xdc-chain/developers/wallet-adapters',
        {type: 'autogenerated', dirName: 'api-reference'},
      ],
    },
    {
      type: 'category',
      label: 'Node Operators & Validators',
      link: {
        type: 'generated-index',
        title: 'Node Operators & Validators',
        description: 'Run XDC infrastructure: masternodes, validator nodes, Docker, Kubernetes, monitoring, and slashing.',
      },
      items: [{type: 'autogenerated', dirName: 'xdc-chain/developers/node-operators'}],
    },
    {
      type: 'category',
      label: 'Enterprise',
      link: {
        type: 'generated-index',
        title: 'Enterprise',
        description: 'XDC for enterprise: trade finance, RWA tokenization, ISO 20022, and private subnets.',
      },
      items: [{type: 'autogenerated', dirName: 'enterprise'}],
    },
    {
      type: 'category',
      label: 'XDC Chain',
      link: {type: 'doc', id: 'xdc-chain/index'},
      items: [
        'xdc-chain/index',
        'xdc-chain/xdpos',
        'xdc-chain/xdpos2',
        'xdc-chain/rewards',
        'xdc-chain/evmtoxdc',
        'xdc-chain/faq',
        'xdc-chain/governance/overview',
      ],
    },
    {
      type: 'category',
      label: 'XDC Subnet',
      link: {
        type: 'generated-index',
        title: 'XDC Subnet',
        description: 'Deploy and operate your own private chain secured by the XDC mainnet.',
      },
      items: [{type: 'autogenerated', dirName: 'subnet'}],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {
        type: 'generated-index',
        title: 'Ecosystem',
        description: 'Join the XDC ecosystem: dApps, DeFi, and RWA platforms.',
      },
      items: [{type: 'autogenerated', dirName: 'ecosystem'}],
    },
    {
      type: 'category',
      label: 'Announcements',
      link: {
        type: 'generated-index',
        title: 'Announcements',
        description: 'Network announcements, upgrade notices, and release news.',
      },
      items: [{type: 'autogenerated', dirName: 'announcements'}],
    },
    {type: 'doc', id: 'whitepaper', label: 'White Paper'},
  ],
};

export default sidebars;
